; this is just a sample. i'm not going to do this but maybe in the future i might want to tweak an extra variable
;https://dev.epicgames.com/documentation/en-us/unreal-engine/scalability-reference-for-unreal-engine
;[FoliageQuality@0]
;foliage.DensityScale=.25
;grass.DensityScale=.25

;[FoliageQuality@1]
;foliage.DensityScale=0.50
;grass.DensityScale=0.50

;[FoliageQuality@2]
;foliage.DensityScale=0.75
;grass.DensityScale=0.75

;[FoliageQuality@3]
;foliage.DensityScale=1.0
;grass.DensityScale=1.0

;----------------
[ViewDistanceQuality@0]
; only ecvf_scalability are allowed. r.Nanite.MaxPixelsPerEdge is ignored but also creates a crash when building
;r.SkeletalMeshLODBias=2 ; these two are defined in baseScalability
;r.ViewDistanceScale=0.4
;r.Nanite.MaxPixelsPerEdge=30

[ViewDistanceQuality@1]
;r.Nanite.MaxPixelsPerEdge=15

[ViewDistanceQuality@2]
;r.Nanite.MaxPixelsPerEdge=7

[ViewDistanceQuality@3]
;r.Nanite.MaxPixelsPerEdge=1

[ViewDistanceQuality@Cine]
;r.Nanite.MaxPixelsPerEdge=1

[ShadowQuality@0]
; i think this has to be power of 2 or it will glitch
r.Forward.LightGridPixelSize=8
; nsot ecvf_scalability
;r.Shadow.Virtual.DynamicRes.MaxPagePoolLoadFactor=0.3
[ShadowQuality@1]
r.Forward.LightGridPixelSize=16
;r.Shadow.Virtual.DynamicRes.MaxPagePoolLoadFactor=0.5
[ShadowQuality@2]
r.Forward.LightGridPixelSize=32
;r.Shadow.Virtual.DynamicRes.MaxPagePoolLoadFactor=0.7
[ShadowQuality@3]
r.Forward.LightGridPixelSize=64
;r.Shadow.Virtual.DynamicRes.MaxPagePoolLoadFactor=0.85
[ShadowQuality@Cine]
r.Forward.LightGridPixelSize=128
;r.Shadow.Virtual.DynamicRes.MaxPagePoolLoadFactor=.9

;---------------

[GlobalIlluminationQuality@0]
r.Lumen.DiffuseIndirect.Allow=0
[GlobalIlluminationQuality@1]
r.Lumen.DiffuseIndirect.Allow=0
[GlobalIlluminationQuality@2]
r.Lumen.DiffuseIndirect.Allow=1
[GlobalIlluminationQuality@3]
r.Lumen.DiffuseIndirect.Allow=1
[GlobalIlluminationQuality@Cine]
r.Lumen.DiffuseIndirect.Allow=1