[/Script/LifeDev.LSysSettings]
Inventory=/Game/LifeDev/Game/Chaps/All/DT_Inventory.DT_Inventory
Characters=/Game/LifeDev/Game/Dialogs/DT_DiagChars.DT_DiagChars
Chapters=/Game/LifeDev/Game/Chaps/All/DT_Chapters.DT_Chapters
StartChap=2
UseDebugFeats=True
DefaultFeats=(C_00,C_01,C_02,C_03,D_ALL,D_TEXT,S_MUSIC,S_NOISE,S_ENV,A_STROBE,V_BLUR)
DebugFeats=(C_00,C_01,C_02,C_03,D_ALL,S_MUSIC,S_NOISE,S_ENV,A_STROBE,DBG_STEPS,DBG_ALL,V_BLUR,DBG_FB,D_TEXT)

[/Script/LifeDev.LChar]
;InteractDrag=.4

[/Script/LifeDev.LFeatsMan]
;FringeIntensity=10
;MotionBlurMax=20
;MotionBlurAmount=2

[/Script/LifeDev.Flashback]
;AnimSpeed = 20

