[ProjectSettings]
ProjectID=(A=1823396784,B=1298598689,C=1743498150,D=-2048051708)
ProjectName=LifeDev

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=E6AD214589424A38A0C51241C3730EFD
CopyrightNotice=Copyright (C) 2023-2025 Jeronimo Barraco-Marmol
ProjectName=LifeDev
CompanyName=Jeronimo Barraco-Marmol
Homepage=jerobarraco.itch.io/LifeDev
ProjectVersion=0.5.4.0
CompanyDistinguishedName=Jeronimo Barraco-Marmol
SupportContact="https://codeberg.org/nande/LifeDev/issues"
ProjectDebugTitleInfo=NSLOCTEXT("[/Script/EngineSettings]", "A08BEE8929B44C35A6944E4E51DE4D63", "{GameName} - {PlatformArchitecture} - {BuildConfiguration}")
Description=A game about CPTSD
ProjectDisplayedTitle=NSLOCTEXT("[/Script/EngineSettings]", "EB12C699EBBE4B35A5746C7B6ADBE0DB", "LifeDev")
bShouldWindowPreserveAspectRatio=False
bUseBorderlessWindow=False

[/Script/Soundscape.SoundscapeSettings]
;SoundscapePaletteCollection=("/Game/LifeDev/Game/Sounds/Rain/SoundsRain.SoundsRain")
bDebugDraw=True
LOD1ColorPointHashWidth=500.000000
LOD1ColorPointHashDistance=5000.000000
LOD2ColorPointHashWidth=2500.000000
LOD2ColorPointHashDistance=10000.000000
LOD3ColorPointHashWidth=10000.000000
ActiveColorPointHashWidth=500.000000
ActiveColorPointHashUpdateTimeSeconds=1.000000

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Development
BuildTarget=LifeDev
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=False
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=True
bUseIoStore=True
bUseZenStore=False
bMakeBinaryConfig=False
bGenerateChunks=False
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bForceOneChunkPerFile=False
MaxChunkSize=0
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
WriteBackMetadataToAssetRegistry=Disabled
bWritePluginSizeSummaryJsons=False
bCompressed=True
PackageCompressionFormat=Oodle
bForceUseProjectCompressionFormatIgnoreHardwareOverride=False
PackageAdditionalCompressionOptions=
PackageCompressionMethod=Kraken
PackageCompressionLevel_DebugDevelopment=4
PackageCompressionLevel_TestShipping=4
PackageCompressionLevel_Distribution=7
PackageCompressionMinBytesSaved=1024
PackageCompressionMinPercentSaved=5
bPackageCompressionEnableDDC=False
PackageCompressionMinSizeToConsiderDDC=0
HttpChunkInstallDataVersion=
IncludePrerequisites=False
IncludeAppLocalPrerequisites=False
bShareMaterialShaderCode=True
bDeterministicShaderCodeOrder=False
bSharedMaterialNativeLibraries=True
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=True
InternationalizationPreset=EFIGSCJK
-CulturesToStage=en
+CulturesToStage=en
LocalizationTargetCatchAllChunkId=0
bCookAll=False
bCookMapsOnly=True
bTreatWarningsAsErrorsOnCook=False
bSkipEditorContent=True
bSkipMovies=False
-IniKeyDenylist=KeyStorePassword
-IniKeyDenylist=KeyPassword
-IniKeyDenylist=DebugKeyStorePassword
-IniKeyDenylist=DebugKeyPassword
-IniKeyDenylist=rsa.privateexp
-IniKeyDenylist=rsa.modulus
-IniKeyDenylist=rsa.publicexp
-IniKeyDenylist=aes.key
-IniKeyDenylist=SigningPublicExponent
-IniKeyDenylist=SigningModulus
-IniKeyDenylist=SigningPrivateExponent
-IniKeyDenylist=EncryptionKey
-IniKeyDenylist=DevCenterUsername
-IniKeyDenylist=DevCenterPassword
-IniKeyDenylist=IOSTeamID
-IniKeyDenylist=SigningCertificate
-IniKeyDenylist=MobileProvision
-IniKeyDenylist=IniKeyDenylist
-IniKeyDenylist=IniSectionDenylist
+IniKeyDenylist=DebugKeyStorePassword
+IniKeyDenylist=DebugKeyPassword
+IniKeyDenylist=KeyStorePassword
+IniKeyDenylist=KeyPassword
+IniKeyDenylist=rsa.privateexp
+IniKeyDenylist=rsa.modulus
+IniKeyDenylist=rsa.publicexp
+IniKeyDenylist=aes.key
+IniKeyDenylist=SigningPublicExponent
+IniKeyDenylist=SigningModulus
+IniKeyDenylist=SigningPrivateExponent
+IniKeyDenylist=EncryptionKey
+IniKeyDenylist=DevCenterUsername
+IniKeyDenylist=DevCenterPassword
+IniKeyDenylist=IOSTeamID
+IniKeyDenylist=SigningCertificate
+IniKeyDenylist=MobileProvision
+IniKeyDenylist=IniKeyDenylist
+IniKeyDenylist=IniSectionDenylist
-IniSectionDenylist=HordeStorageServers
-IniSectionDenylist=StorageServers
-IniSectionDenylist=/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings
+IniSectionDenylist=/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings
+IniSectionDenylist=HordeStorageServers
+IniSectionDenylist=StorageServers
+MapsToCook=(FilePath="/Game/LifeDev/Game/Sys/Game_L")
+MapsToCook=(FilePath="/Game/LifeDev/Intro/Intro_L")
+MapsToCook=(FilePath="/Game/LifeDev/Outro/Outro_L")
+DirectoriesToAlwaysCook=(Path="/NNEDenoiser")
+DirectoriesToNeverCook=(Path="/Game/Test")
+DirectoriesToNeverCook=(Path="/Diags/Test")
+DirectoriesToNeverCook=(Path="/Interact/Tests")
+DirectoriesToNeverCook=(Path="/Inventory/Test")
+DirectoriesToNeverCook=(Path="/JSig/Test")
+DirectoriesToNeverCook=(Path="/JUtils/Test")
+DirectoriesToNeverCook=(Path="/Story/Test")
+DirectoriesToNeverCook=(Path="/Sounds/Test")
+DirectoriesToAlwaysStageAsNonUFS=(Path="Omake")
bRetainStagedDirectory=False
CustomStageCopyHandler=

[Staging]
+AllowedConfigFiles=LifeDev/Config/DefaultLifeDev.ini
+AllowedConfigFiles=LifeDev/Config/DefaultJSig.ini
+AllowedConfigFiles=LifeDev/Config/DefaultInteract.ini
+AllowedConfigFiles=LifeDev/Config/DefaultStory.ini

[/Script/CommonInput.CommonInputSettings]
InputData=/Game/LifeDev/Core/UI/LDInputData.LDInputData_C

[CommonInputPlatformSettings_Linux CommonInputPlatformSettings]
DefaultInputType=MouseAndKeyboard
bSupportsMouseAndKeyboard=True
bSupportsTouch=False
bSupportsGamepad=True
DefaultGamepadName=Generic
bCanChangeGamepadType=True
+ControllerData=/Game/LifeDev/Core/UI/CommonUI/LDControllerData.LDControllerData_C


[/Script/UnrealEd.ProjectPackagingSettings]
; from tom looman. i hope this improve 
bShareMaterialShaderCode=True
bSharedMaterialNativeLibraries=True

