[/Script/LifeDev.LSysSettings]
Inventory=/Game/LifeDev/Game/Inventory/DT_Inventory.DT_Inventory
Characters=/Game/LifeDev/Game/Dialogs/DT_DiagChars.DT_DiagChars
Chapters=/Game/LifeDev/Game/Sys/DT_Chapters.DT_Chapters
StartChap=4
UseDebugFeats=True
UseSaveGame=False
DefaultFeats=(C_00,C_01,C_02,C_03,C_04,C_05,V_STROBE,V_SPEED,V_FOV,V_BLUR,V_FLASHBACK,E_GHOSTPOOL,S_ENV,S_NOISE,S_MUSIC,D_TEXT,V_NANITE,V_MLIGHTS,D_SHOW)
+DebugFeats=C_00
+DebugFeats=C_01
+DebugFeats=C_02
+DebugFeats=C_03
+DebugFeats=C_04
+DebugFeats=C_05
+DebugFeats=E_GHOSTPOOL
+DebugFeats=V_FOV
+DebugFeats=V_STROBE
+DebugFeats=V_FLASHBACK
+DebugFeats=V_BLUR
+DebugFeats=V_SPEED
+DebugFeats=S_ENV
+DebugFeats=S_NOISE
+DebugFeats=S_MUSIC
+DebugFeats=DBG_SIG
+DebugFeats=C_06
+DebugFeats=V_NANITE
+DebugFeats=V_MLIGHTS
+DebugFeats=D_SHOW

[/Script/LifeDev.LChar]
;InteractDrag=.5
;SpeedMin=65
;SpeedMax=150
;SpeedFoxy=10

[/Script/LifeDev.LFeatsMan]
;FringeIntensity=10
;MotionBlurMax=20
;MotionBlurAmount=2

[/Script/LifeDev.Flashback]
;AnimSpeed=20

[/Script/LifeDev.LGGameMode]
; the time for each counter tick. higher = more resources, and more accuracy.
;CounterTime=.5

[/Script/LifeDev.CLCharCam]
;float FOVFoxy = 10;
;float FOVMin = 90;
;float FOVMax = 140;

[/Script/LifeDev.GhostPool]
;float FBMin=.4;
;float TrimTime=60;
;float PoolSizeMin=10;
;float PoolSizeMax=20;

[SectionsToSave]
bCanSaveAllSections=true
;https://forums.unrealengine.com/t/how-to-stop-local-custom-ini-files-being-deleted-after-play/1967813/2
;+Section=???
+Section=CurrentIniVersion

