[/Script/LifeDev.LSysSettings]
CloseURL="https://forms.gle/aYCr8zRR3wWTomyu8"
Items=/Game/LifeDev/Game/Inventory/Items.Items
TeachDTs=((DESK, "/Game/LifeDev/Game/Inventory/Teach/TeachDesk.TeachDesk"),(PAD, "/Game/LifeDev/Game/Inventory/Teach/TeachPad.TeachPad"))
StartChap=0
Chapters=/Game/LifeDev/Game/Dialogs/Chapters.Chapters
Characters=/Game/LifeDev/Game/Dialogs/DiagChars.DiagChars
BaseDiags=/Game/LifeDev/Game/Dialogs/BaseDiags.BaseDiags
BaseGroups=/Game/LifeDev/Game/Dialogs/BaseGroups.BaseGroups
BaseDL=/Game/LifeDev/Game/Sys/DataLayers/Base.Base
+DefaultFeats=V_NANITE
+DefaultFeats=G_TEACH
+DefaultFeats=G_SHOW_POINT
+DefaultFeats=G_SHOW_INV
+DefaultFeats=C_00
+DefaultFeats=C_01
+DefaultFeats=C_02
+DefaultFeats=C_03
+DefaultFeats=C_04
+DefaultFeats=V_STROBE
+DefaultFeats=V_FOV
+DefaultFeats=V_BLUR
+DefaultFeats=V_FLASHBACK
+DefaultFeats=E_GHOSTPOOL
+DefaultFeats=S_ENV
+DefaultFeats=S_NOISE
+DefaultFeats=S_MUSIC
+DefaultFeats=D_TEXT
+DefaultFeats=G_SAVE
+DefaultFeats=G_NGP_FOXY
+DefaultFeats=U_TICK_BATCH
+DefaultFeats=D_SHOW
+DefaultFeats=V_FRINGE
+DefaultFeats=G_CARD0
+DefaultFeats=G_CARD1
+DefaultFeats=G_CARD2
+DefaultFeats=G_CARD3
+DefaultFeats=G_CARD4
+DefaultFeats=G_RUMBLE
+DebugFeats=V_NANITE
+DebugFeats=D_SHOW
+DebugFeats=G_TEACH
+DebugFeats=U_TICK_CON
+DebugFeats=V_FLASHBACK
+DebugFeats=S_NOISE
+DebugFeats=V_BLUR
+DebugFeats=C_04
+DebugFeats=C_03
+DebugFeats=C_02
+DebugFeats=C_01
+DebugFeats=C_00
+DebugFeats=E_GHOSTPOOL
+DebugFeats=V_STROBE
+DebugFeats=V_FOV
+DebugFeats=DBG_BASE
+DebugFeats=G_NGP_FOXY
+DebugFeats=G_SHOW_POINT
+DebugFeats=G_SHOW_INV
+DebugFeats=G_STATUS
+DebugFeats=DBG_FAST_COOL
+DebugFeats=S_MUSIC
+DebugFeats=S_ENV
+DebugFeats=G_FB_ANIM
+DebugFeats=V_FRINGE
+DebugFeats=G_CARD0
+DebugFeats=G_CARD1
+DebugFeats=G_CARD2
+DebugFeats=G_CARD3
+DebugFeats=G_CARD4
+DebugFeats=D_TEXT
+DebugFeats=G_RUMBLE
UseDebugFeats=True

[/Script/LifeDev.LChar]
;InteractDrag=.5
;SpeedMin=65
;SpeedMax=150
;SpeedFoxy=10

[/Script/LifeDev.LFeatsMan]
;FringeIntensity=10
;MotionBlurMax=20
;MotionBlurAmount=2

[/Script/LifeDev.Flashback]
;AnimSpeed=20

[/Script/LifeDev.LGGameMode]
; the time for each counter tick. higher = more resources, and more accuracy.
;CounterTime=.5

[/Script/LifeDev.CLCharCam]
;float FOVFoxy = 10;
;float FOVMin = 90;
;float FOVMax = 140;

[/Script/LifeDev.GhostPool]
;float FBMin=.4;
;float TrimTime=60;
;float PoolSizeMin=10;
;float PoolSizeMax=20;

[/Script/LifeDev.GhostItem]
;FVector OffPos = {0, 0, 30};
;FVector OffDist = {75.0, 75, 75};
;FRotator ActRotOff = {-15, 0, 15};
;float ActRotSpeed = 2.5;
;bool Debug = true;
;float LifeTimeMin=20;
;float LifeTimeMax=30;

[/Script/LifeDev.LDiagMan]
; AutoTime = 2.5

[SectionsToSave]
bCanSaveAllSections=true
;https://forums.unrealengine.com/t/how-to-stop-local-custom-ini-files-being-deleted-after-play/1967813/2
;+Section=???
+Section=CurrentIniVersion

