; this is just a sample. i'm not going to do this but maybe in the future i might want to tweak an extra variable
;https://dev.epicgames.com/documentation/en-us/unreal-engine/scalability-reference-for-unreal-engine
;[FoliageQuality@0]
;foliage.DensityScale=.25
;grass.DensityScale=.25

;[FoliageQuality@1]
;foliage.DensityScale=0.50
;grass.DensityScale=0.50

;[FoliageQuality@2]
;foliage.DensityScale=0.75
;grass.DensityScale=0.75

;[FoliageQuality@3]
;foliage.DensityScale=1.0
;grass.DensityScale=1.0


[ViewDistanceQuality@0]
;r.SkeletalMeshLODBias=2 ; these two are defined in baseScalability
;r.ViewDistanceScale=0.4
r.Nanite.MaxPixelsPerEdge=30

[ViewDistanceQuality@1]
r.Nanite.MaxPixelsPerEdge=15

[ViewDistanceQuality@2]
r.Nanite.MaxPixelsPerEdge=7

[ViewDistanceQuality@3]
r.Nanite.MaxPixelsPerEdge=1

[ViewDistanceQuality@Cine]
r.Nanite.MaxPixelsPerEdge=1
