[/Script/Interact.CInteractor]
; 100 is not enough to reach to stuff on the floor
TraceLen=150
TraceSize=2

[/Script/Interact.CInteract]
;HoverStencilID=10

[/Script/Interact.Interact]
; -1 disabled. 0 the default
;HintPrimDataID=-1
;HintTime=1.5
;HintCurve=Objectpath

[/Script/Interact.AnimMat]
;ShouldBeCreated=true

[SectionsToSave]
bCanSaveAllSections=true
;https://forums.unrealengine.com/t/how-to-stop-local-custom-ini-files-being-deleted-after-play/1967813/2
;+Section=???
+Section=CurrentIniVersion
