//  https://www.youtube.com/watch?v=khblXafu7iA&t=122s
// https://biq.medium.com/configuring-unreal-engine-for-custom-shader-development-biq-cf79f72e7137
// requires setting the path on the project which is done in lifedev.cpp

#define EPSILON 0.0001

// it's a shame but i can't put defaults in structs.
// you need to define an instance and set all these values.

// mom can we have virtual functions?
// no, we have virtual functions at home!
// - The virtual functions at home:
#define DEF_ESTNORMAL() \
float3 EstNormal(float3 pos) {\
	int oid;\
	return normalize( float3(\
		Scene(float3( pos.x + EPSILON, pos.yz), oid )\
		-Scene(float3( pos.x - EPSILON, pos.yz), oid ),\
		Scene(float3( pos.x, pos.y + EPSILON, pos.z), oid )\
		-Scene(float3( pos.x, pos.y - EPSILON, pos.z), oid ),\
		Scene(float3( pos.xy, pos.z + EPSILON), oid )\
		-Scene(float3( pos.xy, pos.z - EPSILON ), oid )\
	));\
};\

#define DEF_MAIN()\
float3 Main(const float stepMax, const float distMax) {\
	float depth = 0.;\
	float dist = 0.0;\
	float3 p = 0.0;\
	int oid = 0;\
	for (int i =0; i<stepMax; ++i) {\
		p = ro + (rd*depth);\
		dist = Scene(p, oid);\
		depth += dist;\
		if (abs(dist)<EPSILON || depth > distMax) break;\
	}\
	const float3 norm = EstNormal(p);\
	const float3 col = SceneCol(depth, p, norm, oid);\
	const float3 fog = Fog(p, col);\
	return fog;\
};\

struct SDF {
	float tt; // time
	float2 uv; // viewport's uv
	float3 ro; // ray origin
	float3 rd; // ray direction

	// unreal stuff
	float edepth; // ue's depth buffer
	float3 enorm;
	float3 evel;
	float4 ecol;
	float3 elpos;
	

	// params, you need to set this because i can´t set defaults.
	float3 ocols[10]; // object's colors. 0 means error
	float specPow; // 10.
	float specStr; // .7
	float3 fogCol; // color
	float fogDist; // absolute
	float fogStr; // 0-1

	float3 SceneCol(const float3 depth, const float3 p, const float3 norm, const int oid) {
		// const float3 norm = estNormal(p);
		const float3 ocol = ocols[oid];
		const float3 scol = Light(elpos, p, norm, ocol, 0.1);
		const float3 col = lerp(ecol.xyz, scol, step(depth, edepth));
		return col;
	}
	
	float3 Light(const float3 lpos, const float3 p, const float3 norm, const float3 col, const float ambient) { 
		// https://michaelwalczyk.com/blog-ray-marching.html

		float3 ldir = normalize(p-lpos);
		float ldiff = max(.0, dot(-ldir, norm));

		float lamb = ambient;

		float3 sdir = reflect(norm, ldir);
		float lspec = pow( clamp(dot(sdir, ldir), 0.0, 1.0 ), specPow)* specStr;
		float rlight = ldiff + lamb;
		float3 rcol = (col * rlight) + lspec;
		return rcol;
	}

	float3 Fog(const float3 p, const float3 scCol) {
		const float camdist = length(p-ro);
		const float normdist = saturate(camdist / fogDist);
		const float str = lerp(0, fogStr, normdist);
		return lerp(scCol, fogCol, str);
	}
};
