//  https://www.youtube.com/watch?v=khblXafu7iA&t=122s
// https://biq.medium.com/configuring-unreal-engine-for-custom-shader-development-biq-cf79f72e7137
// requires setting the path on the project which is done in lifedev.cpp

#define EPSILON 0.0001

// it's a shame but i can't put defaults in structs.
// you need to define an instance and set all these values.

// mom can we have virtual functions?
// no, we have virtual functions at home!
// - The virtual functions at home:
#define DEF_ESTNORMAL() \
float3 estNormal(float3 pos) {\
	int oid;\
	return normalize( float3(\
	scene(float3( pos.x + EPSILON, pos.yz), oid )\
	- scene(float3( pos.x - EPSILON, pos.yz), oid ),\
		scene(float3( pos.x, pos.y + EPSILON, pos.z), oid )\
	- scene(float3( pos.x, pos.y - EPSILON, pos.z), oid ),\
		scene(float3( pos.xy, pos.z + EPSILON), oid )\
	- scene(float3( pos.xy, pos.z - EPSILON ), oid )\
	));\
};\

#define DEF_MAIN()\
float3 main(const float stepMax, const float distMax) {\
	float depth = 0.;\
	float dist = 0.0;\
	float3 p = 0.0;\
	int oid = 0;\
	for (int i =0; i<stepMax; ++i) {\
		p = ro + (rd*depth);\
		dist = scene(p, oid);\
		depth += dist;\
		if (abs(dist)<EPSILON || depth > distMax) break;\
	}\
	const float3 norm = estNormal(p);\
	const float3 col = sceneCol(depth, p, norm, oid);\
	return col;\
};\

struct SDF {
	float tt; // time
	float2 uv; // guess
	float3 ro; // ray origin
	float3 rd; // ray direction

	// unreal stuff
	float edepth; // ue's depth buffer
	float3 enorm;
	float3 evel;
	float4 ecol;
	float3 elpos;
	float3 ocols[10]; // object's colors. 0 means error
	float spec_pow; // 10.
	float spec_str; // .7
	
	//////////
	
	/// shapes
	float sdLink( float3 p, float le, float r1, float r2 ) {
		float3 q = float3( p.x, max(abs(p.y)-le,0.0), p.z );
		return length(float2(length(q.xy)-r1,q.z)) - r2;
	}

	float sdTorus(float3 p, float2 t, float3 pos, float3 rot, float angle) { // inigo
	//  p = rot3(p, rot, angle);
		float2 q = float2(length(p.xz)-t.x,p.y);
		return length(q)-t.y;
	}

	float sdPlane(float3 p, float norm, float d) {
		float3 pn = p*norm;
		return abs(pn.x+pn.y+pn.z+d)/length(norm);
	};

	float sdBox(float3 p, float3 pos, float rot, float3 size) {
		float3 np = p;

		np -=pos;
		np = rot2y(np, rot);

		float3 q = abs(np)-size;

		float dist = length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);
		return dist;
	};
	// scale: multiply p before using. then divide the result.

	float sdGround(float3 p, float dist) {
		return p.z - dist;
	}

	float sdSphere(float3 p, float3 pos, float r) {
		return length(pos-p)-r;
	};

	// inigo
	float dot2( in float2 v ) { return dot(v,v); }
	float dot2( in float3 v ) { return dot(v,v); }
	float ndot( in float2 a, in float2 b ) { return a.x*b.x - a.y*b.y; }
	//// ~inigo

	float3 rot3(float3 p, float3 axis, float angle){
		//rodrigues' rot formula
		return lerp(dot(axis, p)* axis, p, cos(angle) + cross(axis, p) * sin(angle));
	};
	float3 rot2x(float3 p, float a) {
		p.yz= mul(p.yz, rot2(a));
		return p;
	};
	float3 rot2y(float3 p, float a) {
		p.xz= mul(p.xz, rot2(a));
		return p;
	};

	float3 rot2z(float3 p, float a) {
		p.xy = mul(p.xy, rot2(a));
		return p;
	};
	float2x2 rot2(float angle) {
		float s = sin(angle);
		float c = cos(angle);
		
		return float2x2(c, -s, s, c);
	};

	float smin(float a, float b, float k){
		float h = max( k-abs(a-b), 0.0)/k;
		return min(a,b)-pow(h, 3)*k*(1./6.0);
	};
	float3 repeat(float3 p, float by) {
		return fmod(p, by)-.5;
	};
	
	float3 sceneCol(const float3 depth, const float3 p, const float3 norm, const int oid) {
		// const float3 norm = estNormal(p);
		const float3 ocol = ocols[oid];
		const float3 scol = light(elpos, p, norm, ocol, 0.1);
		const float3 col = lerp(ecol.xyz, scol, step(depth, edepth));
		return col;
	}
	
	float3 light(float3 lpos, float3 p, float3 norm, float3 col, float ambient) { 
		// https://michaelwalczyk.com/blog-ray-marching.html

		float3 ldir = normalize(p-lpos);
		float ldiff = max(.0, dot(-ldir, norm));

		float lamb = ambient;

		float3 sdir = reflect(norm, ldir);
		float lspec = pow( clamp(dot(sdir, ldir), 0.0, 1.0 ), spec_pow)* spec_str; // .7;
		float rlight = ldiff + lamb;
		float3 rcol = (col * rlight) + lspec;
		return rcol;
	};

};



