
struct SDFOp {
	float Round(const float obj, float rad ) {
		return obj - rad;
	}
	
	float3 Rot3(const float3 p, const float3 axis, const float angle){
		//rodrigues' rot formula
		// from wikipedia
		return (p*cos(angle))+(cross(axis,p)*sin(angle))+(axis*dot(axis, p)*(1-cos(angle)));
		// doesn't work
		// return lerp(dot(axis, p)* axis, p, cos(angle) + cross(axis, p) * sin(angle));
	}

	float Dot2( in float2 v ) { return dot(v,v); }
	float Dot2( in float3 v ) { return dot(v,v); }
	float Ndot( in float2 a, in float2 b ) { return a.x*b.x - a.y*b.y; }

	float SMin(float a, float b, float k){
		const float h = max( k-abs(a-b), 0.0)/k;
		return min(a,b)-pow(h, 3)*k*(1./6.0);
	}
	float3 Repeat(float3 p, float by) {
		return fmod(p, by)-.5;
	}

	
	float3 rot2x(float3 p, float a) {
		p.yz= mul(p.yz, rot2(a));
		return p;
	};
	float3 rot2y(float3 p, float a) {
		p.xz= mul(p.xz, rot2(a));
		return p;
	};

	float3 rot2z(float3 p, float a) {
		p.xy = mul(p.xy, rot2(a));
		return p;
	};
	float2x2 rot2(float angle) {
		float s = sin(angle);
		float c = cos(angle);
		
		return float2x2(c, -s, s, c);
	};
};

static SDFOp Op;
