//  https://www.youtube.com/watch?v=khblXafu7iA&t=122s
// https://biq.medium.com/configuring-unreal-engine-for-custom-shader-development-biq-cf79f72e7137
// requires setting the path on the project which is done in lifedev.cpp
#include "sdf.usf"
// #include "sdfOp.usf"
#include "sdfShape.usf"

class SDFPost: SDF {
	float Scene(const float3 p, out int oid) {
		float last = -1;
		// float s = sdSphere(p, float3(10, 10, 50), 10);
		float s = Sh.Sphere(p, float3(-200, (10*sin(tt+90)), 100), 10);
		//float s = sdSphere(p, float3(0, 0, 0), 10);
		float b = Sh.Box(p, float3(-210, 0, 100+(10*sin(tt))), sin(tt)*3, float3(10., 10., 8.));
		b = Op.Round(b, 5);
		last = Op.SMin(s, b, 5.0);
		oid = 0;

		float g = Sh.Ground(p, 0.0);
		oid = lerp(1, oid, step(last, g)); // step returns 1 if the 2nd is bigger, 
		last = min(g, last);

		float3 bp = Op.Repeat(p, 25);
		float b2 = Sh.Box(bp, float3(5, 5, 5), sin(tt*.1)*.5*p.y, float3(1., 1., 1.));
		oid = lerp(2, oid, step(last, b2));
		last = min(last, b2);

		SDFObj torO; // no cigar // baby torus
		torO.p = p;
		torO.pos = float3(-50, 20, 30); // 30*sin(tt+90)));
		torO.scale = 4;
		torO.rotAxis = normalize(float3(.1, .1, 1.)); // not confusing at all
		torO.angle = sin(tt)* 5;
		torO.origin = float3(0, 10, 0);
		const float tor = Sh.Torus(torO, float2(4, 1));
		oid = lerp(3, oid, step(last, tor)); // todo extract
		last = min(last, tor); // maybe with this one
		return last;
	};

	DEF_ESTNORMAL()
	DEF_MAIN()
};

SDFPost f;

f.ocols[0] = float3(1, 0, 0);
f.ocols[1] = float3(.1, .9, .1);
f.ocols[2] = float3(.2, .1, .9);
f.ocols[3] = float3(.5, .2, .5);
f.specPow = 15.0;
f.specStr = .5;
f.fogCol = float3(0.1, 0.3, 0.3);
f.fogStr = 1;
f.fogDist = 1000;
