#include "sdfOp.usf"

struct SDFObj {
	float3 p;
	float3 pos;
	float3 scale;
	float3 rotAxis;
	float3 origin;
	float angle;
	
	float3 TransP() {
		// remember to do result*o.scale before returning
		float3 pp = p;
		pp -= pos;
		pp /= scale;
		pp = Op.Rot3(pp, rotAxis, angle);
		pp += origin;
		return pp;
	}
};

struct SDFShape {
	float Torus(SDFObj o, const float2 tr) { // inigo
		float3 p = o.TransP();
		const float2 q = float2(length(p.xz)-tr.x, p.y);
		const float r = length(q)-tr.y;
		return r*length(o.scale);
	}

	// TODO fix. use SDFObj
	
	float Link(const float3 p, const float le, const float r1, const float r2 ) {
		float3 q = float3( p.x, max(abs(p.y)-le,0.0), p.z );
		return length(float2(length(q.xy)-r1,q.z)) - r2;
	}

	float Plane(const float3 p, const float norm, const float d) {
		float3 pn = p*norm;
		return abs(pn.x+pn.y+pn.z+d)/length(norm);
	};

	float Box(const float3 p, const float3 pos, const float rot, const float3 size) {
		float3 np = p;

		np -=pos;
		np = Op.Rot2Y(np, rot);

		float3 q = abs(np)-size;
		const float dist = length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);
		return dist;
	};
	// scale: multiply p before using. then divide the result.

	float Ground(const float3 p, const float dist) {
		return p.z - dist;
	}

	float Sphere(const float3 p, const float3 pos, const float r) {
		return length(pos-p)-r;
	}
};

static SDFShape Sh;