#include "sdfOp.usf"


struct SDFObj {
	float3 p;
	float3 pos;
	float3 scale;
	float3 rotAxis;
	float3 origin;
	float angle;
	
	SDFOp op;

	float3 TransP() {
		// remember to do result*o.scale before returning
		float3 pp = p;
		pp -= pos;
		pp /= scale;
		pp = op.Rot3(pp, rotAxis, angle);
		pp += origin;
		return pp;
	}
};

struct SDFShape {
	SDFOp op;
	float Torus(SDFObj o, const float2 tr) { // inigo
		float3 p = o.TransP();
		const float2 q = float2(length(p.xz)-tr.x, p.y);
		const float r = length(q)-tr.y;
		return r*o.scale;
	}

	// TODO fix

	
	float sdLink( float3 p, float le, float r1, float r2 ) {
		float3 q = float3( p.x, max(abs(p.y)-le,0.0), p.z );
		return length(float2(length(q.xy)-r1,q.z)) - r2;
	}

	float sdPlane(float3 p, float norm, float d) {
		float3 pn = p*norm;
		return abs(pn.x+pn.y+pn.z+d)/length(norm);
	};

	float sdBox(float3 p, float3 pos, float rot, float3 size) {
		float3 np = p;

		np -=pos;
		np = rot2y(np, rot);

		float3 q = abs(np)-size;

		float dist = length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);
		return dist;
	};
	// scale: multiply p before using. then divide the result.

	float sdGround(float3 p, float dist) {
		return p.z - dist;
	}

	float sdSphere(float3 p, float3 pos, float r) {
		return length(pos-p)-r;
	};

};

static SDFShape Sh;